// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiiMqKr9gEv91rLZay8jLyYitT-tN3s7M',
    appId: '1:24097618152:web:b0d48469fb7d6527cb715d',
    messagingSenderId: '24097618152',
    projectId: 'musicplayer-78ab8',
    authDomain: 'musicplayer-78ab8.firebaseapp.com',
    storageBucket: 'musicplayer-78ab8.appspot.com',
    measurementId: 'G-M54M9L4BF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLjeAWT_e_Xw284CEAhZJlNOt6KhXfgco',
    appId: '1:24097618152:android:94cff4ee63f02138cb715d',
    messagingSenderId: '24097618152',
    projectId: 'musicplayer-78ab8',
    storageBucket: 'musicplayer-78ab8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpxgrNpqOXRBlQVzjLlM-Kwj55050mBhw',
    appId: '1:24097618152:ios:22936db7e7009e5fcb715d',
    messagingSenderId: '24097618152',
    projectId: 'musicplayer-78ab8',
    storageBucket: 'musicplayer-78ab8.appspot.com',
    iosBundleId: 'com.example.musicplayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpxgrNpqOXRBlQVzjLlM-Kwj55050mBhw',
    appId: '1:24097618152:ios:22936db7e7009e5fcb715d',
    messagingSenderId: '24097618152',
    projectId: 'musicplayer-78ab8',
    storageBucket: 'musicplayer-78ab8.appspot.com',
    iosBundleId: 'com.example.musicplayer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiiMqKr9gEv91rLZay8jLyYitT-tN3s7M',
    appId: '1:24097618152:web:08e4d31ec4e374a6cb715d',
    messagingSenderId: '24097618152',
    projectId: 'musicplayer-78ab8',
    authDomain: 'musicplayer-78ab8.firebaseapp.com',
    storageBucket: 'musicplayer-78ab8.appspot.com',
    measurementId: 'G-ZQ31KCG566',
  );

}